added tools
HedgeDocs/HedgeDocs.github.io pull request #2
Opened 2022-02-07 20:43 UTC by MichaelHinrichs

SonicGLvl Lost World, Sonic Colors Set Editor, HerosONE, HerosONE Reloaded, Heros Power Plant.

2022-02-07 21:07 UTC, PTKickass requested changes
Thanks for the submission! I have commented some of your edits for things that must be changed before I include them in HedgeDocs. If you have any questions let me know :)

2022-02-07 21:07 UTC, PTKay commented on docs/tools/others/colors/files.md
> +GUI that uses HedgeLib for editing Sonic Colours Set Data.
Different spelling, please either pick Colours or Colors.

2022-02-07 21:07 UTC, PTKay commented on docs/tools/others/heros/files/one.md
> +An objectively superior to all previous tool & library combination for reading and writing .ONE archives from Sonic Heroes and Shadow The Hedgehog.
If this one is better, might as well remove the other one. Keep "HeroesONE Reloaded" and remove the other one.

2022-02-07 21:07 UTC, PTKay commented on docs/tools/others/heros/files/one.md
> +[Download :fontawesome-solid-download:](https://github.com/sonicretro/HeroesONE){ .md-button .md-button--primary target="_blank"}
This should be a "GitHub Repository" button

2022-02-07 21:07 UTC, PTKay commented on docs/tools/others/heros/files/one.md
> +[Download :fontawesome-solid-download:](https://github.com/Sewer56/HeroesONE-Reloaded){ .md-button .md-button--primary target="_blank"}
This file has typos. Please fix:
- Heros -> Heroes
- Reloded -> Reloaded

2022-02-07 21:07 UTC, PTKay commented on docs/tools/others/heros/levels.md
> +[Download :fontawesome-solid-download:](https://github.com/igorseabra4/HeroesPowerPlant){ .md-button .md-button--primary target="_blank"}
This should be a GitHub Repository button

2022-02-07 21:07 UTC, PTKay commented on docs/tools/others/heros/levels.md
> +[Download :fontawesome-solid-download:](https://github.com/igorseabra4/HeroesPowerPlant){ .md-button .md-button--primary target="_blank"}
This file has typos. Please fix:
- Heros -> Heroes

2022-02-07 21:07 UTC, PTKay commented on mkdocs.yml
> +        - Level Editing: tools/hedgehog-engine/lostworld/levels.md
Please use the game's codename for folders. In this case, `sonic2013`.

2022-02-07 21:07 UTC, PTKay commented on mkdocs.yml
> +        - File Formats: tools/others/colors/files.md
Please use the game's codename for folders. In this case, `sonic2010`.

2022-02-07 21:07 UTC, PTKay commented on mkdocs.yml
> +        - Level Editing: tools/others/heros/levels.md
Games should not be grouped together like this. If anything, group them in a `Renderware` section, since both of them use that engine, and remove this from `Other Engines`. For example:

```yaml
- Tools:
    - tools/index.md
    - Hedgehog Engine:
      - Common:
        - File Formats: tools/hedgehog-engine/common/files.md
        - Lighting/GI: tools/hedgehog-engine/common/lighting.md
      - Sonic Generations:
        - File Formats: 
          - XNCP: tools/hedgehog-engine/blueblur/files/xncp.md
          - GTE/GTM: tools/hedgehog-engine/blueblur/files/gte.md
          - AR/ARL: tools/hedgehog-engine/blueblur/files/ar.md
        - Audio: tools/hedgehog-engine/blueblur/audio.md
        - Level Editing: tools/hedgehog-engine/blueblur/levels.md
    - Renderware:
      - Common:
      # sub-sections here
```

Since what you included are common tools for both games, you don't need a dedicated folder/section for each of them, and can just use the common section. See the Hedgehog Engine section for an example.

2022-02-11 20:20 UTC, MichaelHinrichs commented on mkdocs.yml
> +        - Level Editing: tools/others/heros/levels.md
Oh, I didn't know the engine they used. Thank you.

2022-02-12 01:40 UTC, PTKay commented
I'm going to merge this as it is, however, I'll be doing the following changes:
- Fixing up some tool descriptions
- Moving the `heros` folder out of `others` and renaming it to `renderware`

2022-02-12 01:41 UTC, merged