add tools
HedgeDocs/HedgeDocs.github.io pull request #3
Opened 2022-02-14 21:16 UTC by MichaelHinrichs

Generations Archive Editor, GenerationsSkillEdit, PACTool, and Rail Canyon.

2022-03-28 09:16 UTC, PTKickass commented on docs/tools/RSDK/common/files.md
> +[GitHub Repository :fontawesome-brands-github:](https://github.com/Xeeynamo/RSDK){ .md-button target="_blank"}
These should be split into different files whenever possible. So you probably can split Model, File Format and Animation tools into separate archives

2022-03-28 09:29 UTC, PTKickass requested changes
Sorry for the late review. Anyways:

- RSDK should be renamed to retro-engine
- Is sonicRPG the codename for Sonic Adventure?
- There is no proof that Sonic and the Secret Rings uses Renderware, so it should be moved into its own section in the `others` folder. If no mention of the codename for the game is found, just use an abbreviation for the game's name

2022-03-28 09:29 UTC, PTKickass commented on docs/tools/RSDK/common/files.md
> +[GitHub Repository :fontawesome-brands-github:](https://github.com/Xeeynamo/RSDK){ .md-button target="_blank"}
These should be split into different files. So, Model, File Format and Animation tools. If these file formats have a specific file type, then you can just create archives for said file types.

2022-03-28 09:29 UTC, PTKickass commented on docs/tools/Renderware/common/files/txd.md
> +TXD texture archive editor writen with meticulous documentation.
"meticulous documentation" doesn't sound too great. You can simplify this description by just typing this:

```
TXD texture archive editor.
```

Also, isn't there a better way to edit texture for these games nowadays? This seems really old.

2022-03-28 09:29 UTC, PTKickass commented on docs/tools/hedgehog-engine/blueblur/files/ar.md
> +[GitHub Repository :fontawesome-brands-github:](https://github.com/sonicretro/Generations-Archive-Editor){ .md-button target="_blank"}
No need for this, you can remove it. Hedgehog Engine games already have a common archive editor.

2022-03-28 09:29 UTC, PTKickass commented on docs/tools/hedgehog-engine/blueblur/files/sav.md
> +[GitHub Repository :fontawesome-brands-github:](https://github.com/sonicretro/GenerationsSkillEdit){ .md-button target="_blank"}
Save editors are not considered modding tools, so this file should be removed.

2022-03-28 09:29 UTC, PTKickass commented on docs/tools/hedgehog-engine/common/lighting.md
> +Small collection of tools to read, write, and edit .light files for Sonic Unleashed/Generations/Lost World/Forces.
Please change this to
```
Small collection of tools to read, write, and edit .light files for Hedgehog Engine games.
```

2022-03-28 09:29 UTC, PTKickass commented on docs/tools/renderware/common/levels.md
> +[GitHub Repository :fontawesome-brands-github:](https://github.com/DeadlyFugu/rail-canyon){ .md-button target="_blank"}
Any difference between Rail Canyon and HeroesPowerPlant?

If yes, put Rail Canyon on a separate archive for heroes
If not, delete Rail Canyon.

2022-03-28 09:29 UTC, PTKickass commented on mkdocs.yml
> +          - SAV: tools/hedgehog-engine/blueblur/files/sav.md
Remove

2023-11-03 21:19 UTC, PTKay commented
This change will be integrated with a direct push to the repository with the suggested fixes. Thanks for your contribution

2023-11-03 21:19 UTC, closed without merging