Added ModelConverter
HedgeDocs/HedgeDocs.github.io pull request #46
Opened 2023-05-24 23:38 UTC by Knuxfan24

Seems like something that should here.

2023-05-24 23:39 UTC, ActualMandM requested changes
Use `/latest` to direct people to the latest release. Otherwise, LGTM.

2023-05-24 23:39 UTC, ActualMandM commented on docs/tools/hedgehog-engine/common/models.md
> +[Download :fontawesome-solid-download:](https://github.com/blueskythlikesclouds/ModelConverter/releases){ .md-button .md-button--primary}
```suggestion
[Download :fontawesome-solid-download:](https://github.com/blueskythlikesclouds/ModelConverter/releases/latest){ .md-button .md-button--primary}

```

2023-05-24 23:45 UTC, Knuxfan24 commented
The review also made me notice that a few errors had snuck in on the General Audio page too (which is what I copied for reference, hence the lack of /latest in the releases URL).

2023-05-25 01:22 UTC, ActualMandM approved these changes
LGTM

2023-05-25 01:22 UTC, merged