[sonic2013] Add more details for test levels and cutscenes
HedgeDocs/HedgeDocs.github.io pull request #62
Opened 2023-12-03 12:03 UTC by DeaTh-G

2023-12-05 11:42 UTC, PTKay commented on hedgedocs/discoveries/sonic2013/cutscenes/levels.md
> +│   │   ├── ev750
This file needs to be added to the mkdocs index file (`mkdocs.yml`)

2023-12-05 11:43 UTC, PTKay requested changes
The PR seems fine, but the new file will not be seen if you don't add it to the index

2023-12-06 15:47 UTC, DeaTh-G commented
Resolved in 403af33.

2023-12-06 16:26 UTC, PTKay approved these changes
LGTM

2023-12-06 16:26 UTC, merged