[SEGA NN] NodeNameList chunk spec
HedgeDocs/HedgeDocs.github.io pull request #68
Opened 2024-03-14 13:14 UTC by TheExentist151

2024-03-14 23:39 UTC, Radfordhound requested changes
Looks awesome, thanks a lot for helping out!

There's two very minor changes I'd like to make to make it a little easier for devs reading this to tell what the sizes of the fields are. Then, LGTM

2024-03-14 23:39 UTC, Radfordhound commented on hedgedocs/docs/nn/common/chunk-format/nodenamelist.md
> +enum NNE_NODENAME_SORTTYPE
Should probably specify what base type this uses. I forget if this is a uint32_t or a uint8_t that's followed by padding? Only matters for big-endian files.

If you're not sure, don't worry about it, we can just assume it's a uint32_t.

2024-03-14 23:39 UTC, Radfordhound commented on hedgedocs/docs/nn/common/chunk-format/nodenamelist.md
> +    int iNode;
Should probably be int32_t ? (Minor nitpick)

2024-03-15 13:05 UTC, TheExentist151 commented
Thanks for the review! I changed the type of `iNode` in `NNS_NODENAME` struct to uint32_t, because the `nNode` variable is uint32_t too. 

I can't really check the base type of the `NNE_NODENAME_SORTTYPE` struct, but I think this is just a uint32_t.

2024-03-16 06:10 UTC, Radfordhound commented
Thanks, I appreciate it! The base type thing is fine; if we figure it out someday we can just add it in later.

2024-03-16 06:10 UTC, merged

2024-03-16 06:17 UTC, Radfordhound approved these changes